language: cpp

compiler:
    - gcc

before_script:
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo apt-get install -qq
    - sudo apt-get install -y libxxf86vm1 libxxf86vm1 libxxf86vm-dev x11proto-xf86vidmode-dev libxrandr-dev g++-4.8
    - export CXX="g++-4.8" CC="gcc-4.8"
    - mkdir build 
    - cd build
    - cmake ..

script: make